// Mock Data for Smart Food Allocation Optimization System (SDG 2: Zero Hunger)

export const mockStats = {
  totalRescuedKg: 14850,
  mealsProvided: 32900,
  activeDonors: 42,
  recipientShelters: 28,
  activeDeliveries: 7,
  co2SavedKg: 37120,
  urgencyFulfillmentRate: 94.6,
};

export const mockFoodStock = [
  {
    id: 'STK-001',
    donor: 'GreenMarket Supermarket #4',
    donorType: 'Supermarket',
    category: 'Fresh Produce',
    item: 'Organic Apples & Citrus Crates',
    quantity: 180,
    unit: 'kg',
    storageType: 'Cold (4°C)',
    expiryHours: 18,
    status: 'Expiring Soon',
    location: 'North Bay Logistics Hub',
  },
  {
    id: 'STK-002',
    donor: 'Artisan Bakery Co.',
    donorType: 'Bakery',
    category: 'Baked Goods',
    item: 'Whole Wheat Loaves & Baguettes',
    quantity: 120,
    unit: 'loaves',
    storageType: 'Ambient',
    expiryHours: 6,
    status: 'Expiring Soon',
    location: 'Downtown Market St.',
  },
  {
    id: 'STK-003',
    donor: 'City Central Hotel & Catering',
    donorType: 'Hotel / Hospitality',
    category: 'Prepared Meals',
    item: 'Nutritious Rice & Veggie Stew Meals',
    quantity: 250,
    unit: 'boxed meals',
    storageType: 'Heated / Insulated',
    expiryHours: 4,
    status: 'Available',
    location: 'Central Plaza',
  },
  {
    id: 'STK-004',
    donor: 'Valley Dairy Farm',
    donorType: 'Dairy Producer',
    category: 'Dairy',
    item: 'Pasteurized Whole Milk & Yogurt',
    quantity: 300,
    unit: 'liters',
    storageType: 'Refrigerated (2°C)',
    expiryHours: 48,
    status: 'Available',
    location: 'Valley Way Agro Center',
  },
  {
    id: 'STK-005',
    donor: 'SunHarvest Organics',
    donorType: 'Farm',
    category: 'Fresh Produce',
    item: 'Potatoes, Carrots & Leafy Greens',
    quantity: 520,
    unit: 'kg',
    storageType: 'Ambient Cool',
    expiryHours: 96,
    status: 'Available',
    location: 'East Agro Park',
  },
  {
    id: 'STK-006',
    donor: 'Grand Metro Kitchens',
    donorType: 'Restaurant Chain',
    category: 'Prepared Meals',
    item: 'High-Protein Lentil & Quinoa Bowls',
    quantity: 140,
    unit: 'servings',
    storageType: 'Insulated Hot',
    expiryHours: 5,
    status: 'Allocated',
    location: 'Financial District',
  }
];

export const mockDemand = [
  {
    id: 'REQ-101',
    recipient: 'Hope Valley Emergency Shelter',
    recipientType: 'Emergency Shelter',
    beneficiaries: 180,
    urgency: 'Critical',
    neededBy: 'Today, 19:30',
    preferredCategory: 'Prepared Meals',
    dietaryRestrictions: 'Halal, Vegetarian Options',
    distanceKm: 3.8,
    status: 'Pending Match',
  },
  {
    id: 'REQ-102',
    recipient: 'St. Jude Community Kitchen',
    recipientType: 'Community Kitchen',
    beneficiaries: 220,
    urgency: 'High',
    neededBy: 'Today, 21:00',
    preferredCategory: 'Produce & Grains',
    dietaryRestrictions: 'Standard',
    distanceKm: 6.2,
    status: 'Matched',
  },
  {
    id: 'REQ-103',
    recipient: 'Youth & Family Care Center',
    recipientType: 'Community Center',
    beneficiaries: 95,
    urgency: 'High',
    neededBy: 'Tomorrow, 08:00',
    preferredCategory: 'Dairy & Bakery',
    dietaryRestrictions: 'Nut-Free',
    distanceKm: 4.5,
    status: 'Pending Match',
  },
  {
    id: 'REQ-104',
    recipient: 'Elderly Nutrition Aid Network',
    recipientType: 'Senior Aid',
    beneficiaries: 130,
    urgency: 'Medium',
    neededBy: 'Tomorrow, 12:00',
    preferredCategory: 'Fresh Produce & Soups',
    dietaryRestrictions: 'Low Sodium',
    distanceKm: 8.1,
    status: 'Pending Match',
  },
  {
    id: 'REQ-105',
    recipient: 'Harbor Street Mission',
    recipientType: 'Soup Kitchen',
    beneficiaries: 300,
    urgency: 'Critical',
    neededBy: 'Today, 18:45',
    preferredCategory: 'Hot Meals',
    dietaryRestrictions: 'All Inclusive',
    distanceKm: 2.1,
    status: 'Matched',
  }
];

export const mockLocations = [
  {
    id: 'LOC-1',
    name: 'GreenMarket Supermarket #4',
    type: 'DONOR',
    category: 'Supermarket',
    address: '450 North Bay Blvd, Sector 3',
    contactPerson: 'Elena Rostova',
    phone: '+1 (555) 234-8891',
    activeStock: '180 kg',
    lat: 37.7749,
    lng: -122.4194,
    status: 'Active',
  },
  {
    id: 'LOC-2',
    name: 'Hope Valley Emergency Shelter',
    type: 'RECIPIENT',
    category: 'Shelter',
    address: '112 Hope Avenue, Downtown',
    contactPerson: 'Marcus Vance',
    phone: '+1 (555) 982-4112',
    capacity: '200 beds',
    activeStock: 'Needs 180 meals',
    lat: 37.7833,
    lng: -122.4167,
    status: 'Critical Need',
  },
  {
    id: 'LOC-3',
    name: 'City Central Hotel & Catering',
    type: 'DONOR',
    category: 'Hospitality',
    address: '888 Grand Plaza, Financial Dist.',
    contactPerson: 'Chef Antoine Laurent',
    phone: '+1 (555) 432-1100',
    activeStock: '250 boxed meals',
    lat: 37.7891,
    lng: -122.4014,
    status: 'Active',
  },
  {
    id: 'LOC-4',
    name: 'Harbor Street Mission',
    type: 'RECIPIENT',
    category: 'Soup Kitchen',
    address: '29 Harbor Pier Way',
    contactPerson: 'Sister Theresa Chen',
    phone: '+1 (555) 771-3940',
    capacity: '350 meals/day',
    activeStock: 'Needs 300 meals',
    lat: 37.7955,
    lng: -122.3937,
    status: 'Critical Need',
  },
  {
    id: 'LOC-5',
    name: 'SunHarvest Organics Hub',
    type: 'DONOR',
    category: 'Farm / Agro Hub',
    address: '14 Agro Route 9, East County',
    contactPerson: 'David Miller',
    phone: '+1 (555) 610-8201',
    activeStock: '520 kg produce',
    lat: 37.7612,
    lng: -122.3854,
    status: 'Active',
  }
];

export const mockVehicles = [
  {
    id: 'VEH-01',
    plate: 'EV-FOOD-901',
    name: 'Eco-Van Alpha (Electric)',
    type: 'Refrigerated EV Van',
    capacityKg: 800,
    currentLoadKg: 420,
    temperature: '3.4°C',
    battery: '82%',
    driver: 'Samuel Gomez',
    driverPhone: '+1 (555) 301-9988',
    status: 'En Route',
    currentRoute: 'City Central Hotel -> Harbor Street Mission',
    eta: '12 mins',
  },
  {
    id: 'VEH-02',
    plate: 'EV-FOOD-902',
    name: 'Eco-Van Beta (Electric)',
    type: 'Refrigerated EV Van',
    capacityKg: 800,
    currentLoadKg: 0,
    temperature: '4.0°C',
    battery: '95%',
    driver: 'Aisha Al-Mansoor',
    driverPhone: '+1 (555) 301-9989',
    status: 'Available',
    currentRoute: 'Depot - Standby',
    eta: 'Ready',
  },
  {
    id: 'VEH-03',
    plate: 'BIKE-CARGO-12',
    name: 'Rapid Cargo E-Bike 12',
    type: 'Urban Cargo Bike',
    capacityKg: 150,
    currentLoadKg: 110,
    temperature: 'Insulated Bag',
    battery: '74%',
    driver: 'Leo Novak',
    driverPhone: '+1 (555) 301-4455',
    status: 'En Route',
    currentRoute: 'Artisan Bakery -> Youth Care Center',
    eta: '8 mins',
  },
  {
    id: 'VEH-04',
    plate: 'TRK-COLD-05',
    name: 'Heavy Cold Transport 05',
    type: 'Heavy Refrigerated Truck',
    capacityKg: 2500,
    currentLoadKg: 0,
    temperature: '-1°C',
    battery: 'Diesel (80%)',
    driver: 'Boris Petrov',
    driverPhone: '+1 (555) 301-7711',
    status: 'Scheduled',
    currentRoute: 'Valley Dairy Farm -> Central Depot',
    eta: '1 hr 15 mins',
  }
];

export const mockAllocations = [
  {
    id: 'ALC-9821',
    donor: 'City Central Hotel & Catering',
    recipient: 'Harbor Street Mission',
    item: 'Nutritious Rice & Veggie Stew',
    quantity: '250 meals',
    optimizationScore: 98.4,
    distanceKm: 2.1,
    spoilageRiskAvoided: 'Very High',
    assignedVehicle: 'Eco-Van Alpha',
    status: 'In Transit',
    matchedAt: '17:15',
    estimatedArrival: '17:42',
  },
  {
    id: 'ALC-9822',
    donor: 'Artisan Bakery Co.',
    recipient: 'Hope Valley Emergency Shelter',
    item: 'Whole Wheat Loaves',
    quantity: '120 loaves',
    optimizationScore: 95.2,
    distanceKm: 3.4,
    spoilageRiskAvoided: 'High',
    assignedVehicle: 'Rapid Cargo E-Bike 12',
    status: 'Dispatched',
    matchedAt: '17:20',
    estimatedArrival: '17:48',
  },
  {
    id: 'ALC-9823',
    donor: 'GreenMarket Supermarket #4',
    recipient: 'St. Jude Community Kitchen',
    item: 'Apples & Citrus Fruit Crates',
    quantity: '150 kg',
    optimizationScore: 92.8,
    distanceKm: 5.7,
    spoilageRiskAvoided: 'Moderate',
    assignedVehicle: 'Eco-Van Beta',
    status: 'Optimized',
    matchedAt: '17:28',
    estimatedArrival: '18:15',
  }
];

export const mockAlerts = [
  {
    id: 'ALT-1',
    severity: 'CRITICAL',
    title: 'Perishable Food Expiry Imminent (4 Hours Left)',
    message: '250 hot boxed meals at City Central Hotel must be dispatched immediately to prevent spoilage.',
    timestamp: '10 mins ago',
    source: 'Automated Expiry Monitor',
    actionRequired: 'Confirm Allocation ALC-9821',
  },
  {
    id: 'ALT-2',
    severity: 'HIGH',
    title: 'Surge In Emergency Shelter Demand',
    message: 'Hope Valley Emergency Shelter reported 40 additional vulnerable individuals requiring evening nourishment.',
    timestamp: '25 mins ago',
    source: 'Demand Prediction Engine',
    actionRequired: 'Re-balance produce allocation',
  },
  {
    id: 'ALT-3',
    severity: 'MEDIUM',
    title: 'Cold-Chain Temperature Alert',
    message: 'Eco-Van Alpha sensor reported 3.4°C (Safe threshold: 4.0°C). Temperature nearing limit.',
    timestamp: '42 mins ago',
    source: 'Vehicle Telemetry IoT',
    actionRequired: 'Monitor cooling unit',
  },
  {
    id: 'ALT-4',
    severity: 'INFO',
    title: 'New Organic Farm Donor Onboarded',
    message: 'SunHarvest Organics connected 520 kg surplus root vegetables ready for collection.',
    timestamp: '1 hour ago',
    source: 'Donor Portal',
    actionRequired: 'Inspect route grouping',
  }
];

export const mockHistory = [
  {
    id: 'HIST-2041',
    date: '2026-09-24',
    donor: 'Metro Grocery Hub 12',
    recipient: 'Family Shelter West',
    foodItem: 'Mixed Fresh Fruits & Dairy',
    quantityRescued: '340 kg',
    mealsServed: 755,
    co2PreventedKg: 850,
    deliveryTimeMinutes: 28,
    score: 97.2,
  },
  {
    id: 'HIST-2040',
    date: '2026-09-24',
    donor: 'Skyline Convention Banquets',
    recipient: 'St. Anthony Dining Room',
    foodItem: 'Chef Prepared Buffet Trays',
    quantityRescued: '410 meals',
    mealsServed: 410,
    co2PreventedKg: 1025,
    deliveryTimeMinutes: 22,
    score: 99.1,
  },
  {
    id: 'HIST-2039',
    date: '2026-09-23',
    donor: 'Golden Crust Bakery',
    recipient: 'Community Youth Oasis',
    foodItem: 'Assorted Artisan Bread',
    quantityRescued: '180 loaves',
    mealsServed: 360,
    co2PreventedKg: 450,
    deliveryTimeMinutes: 19,
    score: 94.8,
  },
  {
    id: 'HIST-2038',
    date: '2026-09-23',
    donor: 'Pacific Coast Fishery Outlet',
    recipient: 'Harbor Street Mission',
    foodItem: 'Chilled Fish Fillets (Canned/Packed)',
    quantityRescued: '220 kg',
    mealsServed: 490,
    co2PreventedKg: 660,
    deliveryTimeMinutes: 35,
    score: 91.5,
  }
];

export const mockAdminConfig = {
  algorithmWeights: {
    urgencyPriority: 45,
    shelfLifeDecay: 35,
    distanceMinimization: 20,
  },
  temperatureSafetyLimit: 4.0,
  autoDispatchThresholdScore: 92.0,
  sdg2GoalTargetMeals: 50000,
  co2ConversionFactorKgPerKgFood: 2.5,
};
